<?php

namespace Database\Seeders;

use Hash;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'daniel',
                'email' => 'daniel@gmail.com',
                'email_verified_at' => now(),
                'password' => 'password1',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'adom',
                'email' => 'adom@example.com',
                'email_verified_at' => now(),
                'password' => 'password2',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'islam',
                'email' => 'islam@example.com',
                'email_verified_at' => now(),
                'password' => 'password3',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'langoe',
                'email' => 'langoe@example.com',
                'email_verified_at' => now(),
                'password' => 'password4',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chabane',
                'email' => 'chabane@example.com',
                'email_verified_at' => now(),
                'password' => 'password5',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'alassani',
                'email' => 'alassani@example.com',
                'email_verified_at' => now(),
                'password' => 'password6',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'soka',
                'email' => 'soka@example.com',
                'email_verified_at' => now(),
                'password' => 'password7',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'rachad',
                'email' => 'rachad@example.com',
                'email_verified_at' => now(),
                'password' => 'password8',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'fad',
                'email' => 'fad@example.com',
                'email_verified_at' => now(),
                'password' => 'password9',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sarata',
                'email' => 'sarata@example.com',
                'email_verified_at' => now(),
                'password' => 'password10',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'crepin',
                'email' => 'crepin@example.com',
                'email_verified_at' => now(),
                'password' => 'password11',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'farida',
                'email' => 'farida@example.com',
                'email_verified_at' => now(),
                'password' => 'password12',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'toyi',
                'email' => 'toyi@example.com',
                'email_verified_at' => now(),
                'password' => 'password13',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'gilbert',
                'email' => 'gilbert@example.com',
                'email_verified_at' => now(),
                'password' => 'password14',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mangba',
                'email' => 'mangba@example.com',
                'email_verified_at' => now(),
                'password' => 'password15',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'patrick',
                'email' => 'patrick@example.com',
                'email_verified_at' => now(),
                'password' => 'password16',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'damso',
                'email' => 'damso@example.com',
                'email_verified_at' => now(),
                'password' => 'password17',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'yerima',
                'email' => 'yerima@example.com',
                'email_verified_at' => now(),
                'password' => 'password18',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'aliya',
                'email' => 'aliya@example.com',
                'email_verified_at' => now(),
                'password' => 'password19',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'zina',
                'email' => 'zina@example.com',
                'email_verified_at' => now(),
                'password' => 'password20',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'agao',
                'email' => 'agao@example.com',
                'email_verified_at' => now(),
                'password' => 'password21',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'baba',
                'email' => 'baba@example.com',
                'email_verified_at' => now(),
                'password' => 'password22',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'aimane',
                'email' => 'aimane@example.com',
                'email_verified_at' => now(),
                'password' => 'password23',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'essoronda',
                'email' => 'essoronda@example.com',
                'email_verified_at' => now(),
                'password' => 'password24',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'arouna',
                'email' => 'arouna@example.com',
                'email_verified_at' => now(),
                'password' => 'password25',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'fatiha',
                'email' => 'fatiha@example.com',
                'email_verified_at' => now(),
                'password' => 'password26',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'name' => 'bokopolo',
                'email' => 'bokopolo@example.com',
                'email_verified_at' => now(),
                'password' => 'password27',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'name' => 'guema',
                'email' => 'guema@example.com',
                'email_verified_at' => now(),
                'password' => 'password28',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'dado',
                'email' => 'dado@example.com',
                'email_verified_at' => now(),
                'password' => 'password29',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nabila',
                'email' => 'nabila@example.com',
                'email_verified_at' => now(),
                'password' => 'password30',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chakour',
                'email' => 'chakour@example.com',
                'email_verified_at' => now(),
                'password' => 'password31',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'stephani',
                'email' => 'stephani@example.com',
                'email_verified_at' => now(),
                'password' => 'password32',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'grace',
                'email' => 'grace@example.com',
                'email_verified_at' => now(),
                'password' => 'password33',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'gisele',
                'email' => 'gisele@example.com',
                'email_verified_at' => now(),
                'password' => 'password34',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mechac',
                'email' => 'mechac@example.com',
                'email_verified_at' => now(),
                'password' => 'password35',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'donne',
                'email' => 'donne@example.com',
                'email_verified_at' => now(),
                'password' => 'password36',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'godwin',
                'email' => 'godwin@example.com',
                'email_verified_at' => now(),
                'password' => 'password37',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'abdel',
                'email' => 'abdel@example.com',
                'email_verified_at' => now(),
                'password' => 'password38',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'christophe',
                'email' => 'christophe@example.com',
                'email_verified_at' => now(),
                'password' => 'password39',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'faozial1',
                'email' => 'faozial1@example.com',
                'email_verified_at' => now(),
                'password' => 'password40',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'karine',
                'email' => 'karine@example.com',
                'email_verified_at' => now(),
                'password' => 'password41',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'rahme',
                'email' => 'rahme@example.com',
                'email_verified_at' => now(),
                'password' => 'password42',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'floriant',
                'email' => 'floriant@example.com',
                'email_verified_at' => now(),
                'password' => 'password43',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ganietou',
                'email' => 'ganietou@example.com',
                'email_verified_at' => now(),
                'password' => 'password44',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'essofa',
                'email' => 'user45@example.com',
                'email_verified_at' => now(),
                'password' => 'password45',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'rafiat',
                'email' => 'rafiat@example.com',
                'email_verified_at' => now(),
                'password' => 'password46',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'rahate',
                'email' => 'rahate@example.com',
                'email_verified_at' => now(),
                'password' => 'password47',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chakira',
                'email' => 'chakira@example.com',
                'email_verified_at' => now(),
                'password' => 'password48',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'youssif',
                'email' => 'youssif@example.com',
                'email_verified_at' => now(),
                'password' => 'password49',
                'remember_token' => bin2hex(random_bytes(5)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];
        

        foreach ($users as &$user) {
            $user['password'] = Hash::make($user['password']);
        }

        DB::table('users')->insert($users);
    }
}
